# Required
version: 2

# Dependencies
build:
  os: ubuntu-20.04
  tools:
    python: "3.6"
  apt_packages:
    - build-essential
    - cmake
    - doxygen
    - graphviz
    - libeigen3-dev
  jobs:
    pre_build:
        - bash ./docs/doxygen/build.bash

# Sphinx config
sphinx:
  configuration: docs/sphinx/source/conf.py

# Python requirements
python:
  install:
    - requirements: requirements.develop.txt
